"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
import truststore
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Verify outbound TLS against the operating system's trust store rather than
# the bundled certifi list, so machines behind an HTTPS-inspecting proxy or
# antivirus can still reach the routing APIs with verification left on.
truststore.inject_into_ssl()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

# The fallback key only exists so a fresh clone runs without any setup. It is
# never used to protect stored credentials (see CREDENTIALS_ENCRYPTION_KEYS).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off.')
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'planner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# PostgreSQL when DATABASE_URL is set (docker compose sets it); otherwise a
# local SQLite file so a fresh clone runs with no services installed.
if os.environ.get('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Under gunicorn nothing serves the admin's CSS unless WhiteNoise does. It is
# only switched on once collectstatic has run (the Docker image does that);
# runserver serves static files itself.
if STATIC_ROOT.is_dir():
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')


# HTTPS hardening for a deployment behind a TLS-terminating proxy or load
# balancer. Off by default so the local stack works over plain http.
if os.environ.get('DJANGO_SECURE', '').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [r'^healthz/$']  # health checks arrive over plain http
    # includeSubDomains and preload are left off: they commit a whole domain,
    # which is not this service's decision to make.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', 3600))
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Django REST framework: JSON only, no auth (the brief asks for an open API).
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'EXCEPTION_HANDLER': 'planner.handlers.api_exception_handler',
}

# Requests per client on the route endpoint, e.g. "120/min". Empty disables it.
API_RATE_LIMIT = os.environ.get('API_RATE_LIMIT', '120/min')
# Sign-in attempts per client, to slow down password guessing.
LOGIN_RATE_LIMIT = os.environ.get('LOGIN_RATE_LIMIT', '10/min')

# Redis when REDIS_URL is set, so every worker shares one route cache;
# otherwise a per-process cache that needs no service. The test suite clears
# the cache freely, so it always gets a private one.
if os.environ.get('REDIS_URL') and sys.argv[1:2] != ['test']:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
            'KEY_PREFIX': 'fuelroute',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'OPTIONS': {'MAX_ENTRIES': 500},
        }
    }


# Django Debug Toolbar: the SQL, cache calls and timing behind every request,
# including the API calls the map page makes (its History panel lists them).
# It shows the inside of the server to whoever can reach it, so it is opt-in:
# the local docker compose stack turns it on and nothing else should. It is
# never loaded for the test suite.
DEBUG_TOOLBAR = (
    os.environ.get('DJANGO_DEBUG_TOOLBAR', '').lower() in ('1', 'true', 'yes') and sys.argv[1:2] != ['test']
)
if DEBUG_TOOLBAR:
    if os.environ.get('DJANGO_SECURE', '').lower() in ('1', 'true', 'yes'):
        raise ImproperlyConfigured('DJANGO_DEBUG_TOOLBAR must not be set on a deployment (DJANGO_SECURE is on).')
    INSTALLED_APPS.append('debug_toolbar')
    # After GZip, so the toolbar is added to a page before the page is compressed.
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.gzip.GZipMiddleware') + 1,
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )
    # The panels that say something about this service. Each one costs a little
    # on every request, so the rest (versions, signals, static files, tasks...)
    # are left out.
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
    ]
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'config.toolbar.show_toolbar',
        'SHOW_COLLAPSED': True,   # a small handle on the edge of the page until it is clicked
        'UPDATE_ON_FETCH': True,  # follow the page's API calls, so the panels describe the plan on screen
        'RESULTS_CACHE_SIZE': 50,
    }
    if os.environ.get('REDIS_URL'):
        # With Redis, what the toolbar records is kept there, so that either
        # gunicorn worker can show a request the other one served. It gets a
        # cache of its own: when it shares the application's, the Cache panel
        # never sees the application's own cache calls.
        CACHES['toolbar'] = {**CACHES['default'], 'KEY_PREFIX': 'djdt'}
        DEBUG_TOOLBAR_CONFIG.update(TOOLBAR_STORE_CLASS='debug_toolbar.store.CacheStore', CACHE_BACKEND='toolbar')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {'planner': {'handlers': ['console'], 'level': 'INFO'}},
}


# Fuel route planner

DATA_DIR = BASE_DIR / 'data'
FUEL_PRICES_CSV = DATA_DIR / 'fuel-prices-for-be-assessment.csv'
CENSUS_PLACES_ZIP = DATA_DIR / 'census' / '2025_Gaz_place_national.zip'
NOMINATIM_CACHE = DATA_DIR / 'nominatim_cache.json'

# Comma separated Fernet keys used to encrypt provider API keys in the
# database. The first key encrypts; all keys can decrypt, which allows rotation.
# Generate one with: python manage.py generate_encryption_key
CREDENTIALS_ENCRYPTION_KEYS = [
    k.strip() for k in os.environ.get('CREDENTIALS_ENCRYPTION_KEYS', '').split(',') if k.strip()
]

# How long a route from the routing provider is reused, in seconds.
ROUTE_CACHE_SECONDS = int(os.environ.get('ROUTE_CACHE_SECONDS', 3600))
ROUTING_TIMEOUT_SECONDS = float(os.environ.get('ROUTING_TIMEOUT_SECONDS', 20))
OSRM_BASE_URL = os.environ.get('OSRM_BASE_URL', 'https://router.project-osrm.org').rstrip('/')
ORS_BASE_URL = os.environ.get('ORS_BASE_URL', 'https://api.openrouteservice.org').rstrip('/')
