# Generated by Django 6.1.2 on 2026-10-06 22:18

import django.db.models.deletion
import planner.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('osrm', 'OSRM public server (no key)'), ('openrouteservice', 'OpenRouteService (API key)')], max_length=32, unique=True)),
                ('api_key', planner.crypto.EncryptedTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('routing.provider', 'routing.provider'), ('stations.corridor_miles', 'stations.corridor_miles'), ('vehicle.range_miles', 'vehicle.range_miles'), ('vehicle.mpg', 'vehicle.mpg'), ('stops.cost_per_stop', 'stops.cost_per_stop')], max_length=64, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('key', models.CharField(help_text='Normalised name used for matching.', max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('land_sqmi', models.FloatField(default=0, help_text='Breaks ties between places sharing a name.')),
                ('is_alias', models.BooleanField(default=False, help_text='Short form of a consolidated name, e.g. Nashville for Nashville-Davidson.')),
                ('source', models.CharField(choices=[('census', 'Census Gazetteer'), ('nominatim', 'Nominatim (OpenStreetMap)')], default='census', max_length=12)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'state'], name='place_key_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lat__gte', -90), ('lat__lte', 90)), name='place_lat_in_range'), models.CheckConstraint(condition=models.Q(('lon__gte', -180), ('lon__lte', 180)), name='place_lon_in_range')],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=5, help_text='USD per gallon; mean of the rows sharing this OPIS ID.', max_digits=8)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='planner.place')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='fuelstation_price_positive')],
            },
        ),
    ]
