# Generated by Django 6.1.2 on 2026-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_seed_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['key'], name='place_key_prefix_idx', opclasses=['varchar_pattern_ops']),
        ),
    ]
